# Generated by Django 3.1.6 on 2021-02-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.IntegerField()),
                ('courseName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('classHr', models.IntegerField()),
                ('NoofQuery', models.IntegerField()),
                ('ResponseTime', models.IntegerField()),
                ('SubmissionDate', models.IntegerField()),
            ],
        ),
    ]
